#  get http://localhost:8080/locations

# get http://localhost:8080/locations/2

DELETE http://localhost:8080/locations/2


# PUT  http://127.0.0.1:8080/locations/1
# Content-Type: application/json

# {
#     "latitude": 70,
#     "longitude": 80
# }



PATCH  http://127.0.0.1:8080/locations/2
Content-Type: application/json

{
    "latitude": 70,
    "longitude": 80
}
